import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import basicSsl from '@vitejs/plugin-basic-ssl'
import { VitePWA } from 'vite-plugin-pwa'

// Camera access needs HTTPS on phones, so dev runs on a self-signed cert (basic-ssl).
// `npm run dev` passes --host so phones on the LAN can reach it. /api goes to the backend
// through the same origin, so there is no mixed content and no CORS.
// The PWA service worker only exists in builds (npm run build / preview), not in dev.
export default defineConfig({
  plugins: [
    react(),
    basicSsl(),
    VitePWA({
      // src/pwa.ts registers the worker and applies updates only from Setup, never mid-game.
      registerType: 'prompt',
      injectRegister: false,
      manifest: {
        name: 'Impostor',
        short_name: 'Impostor',
        description: 'Ordspel där en av er är bedragaren. Skicka runt telefonen.',
        lang: 'sv',
        display: 'standalone',
        orientation: 'portrait',
        start_url: '/',
        scope: '/',
        // Same as --bg in tokens.css.
        theme_color: '#14122B',
        background_color: '#14122B',
        // Generated by `npm run icons` from public/icon.svg.
        icons: [
          { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          { src: 'maskable-icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,ico,woff2}'],
        navigateFallback: '/index.html',
        // The API is never cached: words, logins and stats always come from the server.
        navigateFallbackDenylist: [/^\/api\//],
        runtimeCaching: [
          {
            urlPattern: ({ url }) => url.origin === 'https://fonts.googleapis.com',
            handler: 'StaleWhileRevalidate',
            options: { cacheName: 'google-fonts-css' },
          },
          {
            urlPattern: ({ url }) => url.origin === 'https://fonts.gstatic.com',
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts',
              expiration: { maxEntries: 20, maxAgeSeconds: 365 * 24 * 3600 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
  server: {
    proxy: {
      '/api': 'http://localhost:8000',
    },
  },
  test: {
    environment: 'node',
    include: ['src/**/*.test.ts'],
  },
})
